# curl -XPUT 'http://localhost:9200/bizcuit/' -d '
settings:
  index:
    number_of_shards: 5
    number_of_replicas: 1
    analysis:
      analyzer:
        bizcuit_standard:
          tokenizer: standard
          filter:
          - standard
          - lowercase
          - word_delimiter
          - asciifolding
        bizcuit_language_stemmer:
          tokenizer: standard
          filter:
          - standard
          - lowercase
          - word_delimiter
          - asciifolding
          - english_stemmer
        bizcuit_edge_ngram:
          tokenizer: standard
          filter:
          - standard
          - lowercase
          - word_delimiter
          - asciifolding
          - edge_ngram
      filter:
        english_stemmer:
          type: stemmer
          language: english
        edge_ngram:
          type: edgeNGram
          min_gram: 2
          max_gram: 8
          token_chars:
          - letter
          - digit
mappings:
  client:
    dynamic: strict
    properties:
      first_name:
        type: string
        index: analyzed
        analyzer: bizcuit_standard
        fields:
          edge_ngram:
            type: string
            index: analyzed
            search_analyzer: bizcuit_standard
            index_analyzer: bizcuit_edge_ngram
      last_name:
        type: string
        index: analyzed
        analyzer: bizcuit_standard
        fields:
          edge_ngram:
            type: string
            search_analyzer: bizcuit_standard
            index_analyzer: bizcuit_edge_ngram
      email:
        type: string
        index: analyzed
        analyzer: bizcuit_standard
        fields:
          edge_ngram:
            type: string
            search_analyzer: bizcuit_standard
            index_analyzer: bizcuit_edge_ngram
      phone:
        type: string
        index: analyzed
        analyzer: standard
      note:
        type: string
        index: analyzed
        analyzer: bizcuit_standard
        fields:
          edge_ngram:
            type: string
            search_analyzer: bizcuit_standard
            index_analyzer: bizcuit_edge_ngram
          language_stemmer:
            type: string
            analyzer: bizcuit_language_stemmer
      address:
        type: object
        properties:
          number:
            # Needs to be string because address numbers can contain letters
            type: string
            index: not_analyzed
          street:
            type: string
            index: analyzed
            analyzer: bizcuit_standard
            fields:
              edge_ngram:
                type: string
                search_analyzer: bizcuit_standard
                index_analyzer: bizcuit_edge_ngram
              language_stemmer:
                type: string
                analyzer: bizcuit_language_stemmer
          suite:
            type: string
            index: not_analyzed
          city:
            type: string
            index: analyzed
            analyzer: bizcuit_standard
            fields:
              edge_ngram:
                type: string
                search_analyzer: bizcuit_standard
                index_analyzer: bizcuit_edge_ngram
              language_stemmer:
                type: string
                analyzer: bizcuit_language_stemmer
          province:
            type: string
            index: analyzed
            analyzer: bizcuit_standard
            fields:
              edge_ngram:
                type: string
                search_analyzer: bizcuit_standard
                index_analyzer: bizcuit_edge_ngram
          postal_code:
            type: string
            index: analyzed
            analyzer: bizcuit_standard
            fields:
              edge_ngram:
                type: string
                search_analyzer: bizcuit_standard
                index_analyzer: bizcuit_edge_ngram
      created:
        type: date
        index: not_analyzed
